DROP SCHEMA IF EXISTS `shop`;

-- MySQL Script generated by MySQL Workbench
-- 06/28/16 15:06:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(96) NULL,
  `telephone` VARCHAR(15) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `address_id` INT NULL,
  `date_added` DATE NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `model` VARCHAR(255) NULL,
  `quantity` INT NULL,
  `price` DOUBLE NULL,
  `image` VARCHAR(255) NULL,
  `status` INT NULL,
  `date_added` DATE NULL,
  `date_modified` DATE NULL,
  PRIMARY KEY (`product_id`),
  INDEX `category_id_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_id_product`
    FOREIGN KEY (`category_id`)
    REFERENCES `shop`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `telephone` VARCHAR(15) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `comment` TEXT NULL,
  `status` VARCHAR(45) NOT NULL,
  `total` VARCHAR(45) NULL,
  `date_added` DATE NULL,
  `date_modified` DATE NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_id_order`
    FOREIGN KEY (`customer_id`)
    REFERENCES `shop`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`order_item` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `model` VARCHAR(255) NULL,
  `quantity` INT NULL,
  `price` DOUBLE NULL,
  `total` DOUBLE NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `order_id_idx` (`order_id` ASC),
  INDEX `product_id_idx` (`product_id` ASC),
  CONSTRAINT `fk_order_id_order_item`
    FOREIGN KEY (`order_id`)
    REFERENCES `shop`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_id_order_item`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`customer_to_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`customer_to_address` (
  `customer_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  INDEX `customer_id_idx` (`customer_id` ASC),
  INDEX `address_id_idx` (`address_id` ASC),
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `shop`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `shop`.`address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`specification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`specification` (
  `spec_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`spec_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`product_to_spec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`product_to_spec` (
  `product_id` INT NOT NULL,
  `spec_id` INT NOT NULL,
  `value` VARCHAR(255) NULL,
  INDEX `product_id_idx` (`product_id` ASC),
  INDEX `spec_id_idx` (`spec_id` ASC),
  CONSTRAINT `fk_product_id_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spec_id`
    FOREIGN KEY (`spec_id`)
    REFERENCES `shop`.`specification` (`spec_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

alter table shop.product_to_spec
add column product_spec_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

alter table shop.product_to_spec
add column spec_name VARCHAR(255);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
